name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtualenv
        run: |
          which python
          python -m venv venv
          source venv/bin/activate
          python -m pip install --constraint=.github/workflows/constraints.txt --upgrade pip setuptools
          which python

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          which python
          pip install -r requirements.txt
          pip install -r requirements-cli.txt
          pip install -r requirements-dev.txt

      - name: Compute pre-commit cache key
        id: pre-commit-cache
        shell: python
        run: |
          import hashlib
          import os
          import sys
          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = "${{ runner.os }}-{}-{}-pre-commit".format(python, digest[:8])
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              print(f"result={result}", file=fh)

      - name: Restore pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.pre-commit-cache.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ steps.pre-commit-cache.outputs.result }}-

      - name: pre-commit
        run: |
          source venv/bin/activate
          pre-commit run --hook-stage=manual --show-diff-on-failure --all-files

      # - name: mypy
      #   run: mypy .

      - name: pytest
        # run: pytest --junitxml=junit.xml --cov --cov-report=term-missing:skip-covered --cov-report=xml
        run: |
          source venv/bin/activate
          pytest
